import { programContent } from "./types";

export const YearTwoITFirstSem: programContent = {
  header: "Level 200 First Semester (IT)",
  description: "",
  courses: [
    {
      id: 1,
      code: "CBAS 210",
      title: "Academic Writing II",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 2,
      code: "DCIT 201",
      title: "Programming I",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 3,
      code: "DCIT 203",
      title: "Digital and Logic Systems Design",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 4,
      code: "DCIT 205",
      title: "Multi Media and Web Design",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 5,
      code: "DCIT 207",
      title: "Computer Organization and Architecture",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 6,
      code: "DCIT 209",
      title: "E-Business Architectures",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
  ],
};

export const YearThreeITFirstSem: programContent = {
  header: "Level 300 First Semester (IT)",
  description:
    "* Select 3-6 credits from the elective courses in addition to the core courses *",
  courses: [
    {
      id: 7,
      code: "DCIT 301",
      title: "Operating Systems",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 8,
      code: "DCIT 303",
      title: "Computer Networks",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 9,
      code: "DCIT 305",
      title: "Database Fundamentals",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 10,
      code: "DCIT 313",
      title: "Introduction to Artificial Intelligence",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 11,
      code: "DCIT 317",
      title: "IT Project Management",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 12,
      code: "DCIT 307",
      title: "Mini-Project",
      credits: 1,
      preRequisite: "",
      type: "core",
    },
    {
      id: 12,
      code: "DCIT 315",
      title: "Principles of 3D Environment",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
    {
      id: 12,
      code: "DCIT 321",
      title: "Software Evolution",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
  ],
};

export const YearFourITFirstSem: programContent = {
  header: "Level 400 First Semester (IT)",
  description:
    "* Select 9-12 credits from the elective courses in addition to the core courses *",
  courses: [
    {
      id: 13,
      code: "DCIT 400",
      title: "Project",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 14,
      code: "DCIT 401",
      title: "Social, Legal, Ethical and Professional Issues",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 15,
      code: "DCIT 409",
      title: "Digital Forensics",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 16,
      code: "DCIT 413",
      title: "Play and Games",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
    {
      id: 17,
      code: "DCIT 415",
      title: "Advanced Software Engineering",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
    {
      id: 18,
      code: "DCIT 419",
      title: "Agile Methods",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
    {
      id: 20,
      code: "DCIT 421",
      title: "Persuasive Systems Development",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
  ],
};
