import { programContent } from "./types";

export const YearTwoSMFirstSem: programContent = {
  header: "Level 200 First Semester (Single Major)",
  description: "",
  courses: [
    {
      id: 1,
      code: "CBAS 210",
      title: "Academic Writing II",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 2,
      code: "DCIT 201",
      title: "Programming I",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 3,
      code: "DCIT 203",
      title: "Digital and Logic Systems Design",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 4,
      code: "DCIT 205",
      title: "Multi Media and Web Design",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 5,
      code: "DCIT 207",
      title: "Computer Organization and Architecture",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 6,
      code: "MATH 223",
      title: "Calculus II",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
  ],
};

export const YearThreeSMFirstSem: programContent = {
  header: "Level 300 First Semester (Single Major)",
  description:
    "* Select 3-6 credits from the elective courses in addition to the core courses *",
  courses: [
    {
      id: 7,
      code: "DCIT 301",
      title: "Operating Systems",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 8,
      code: "DCIT 303",
      title: "Computer Networks",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 9,
      code: "DCIT 305",
      title: "Database Fundamentals",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 10,
      code: "DCIT 313",
      title: "Introduction to Artificial Intelligence",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 11,
      code: "MATH 359",
      title: "Discrete Mathematics",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 12,
      code: "DCIT 307",
      title: "Mini-Project",
      credits: 1,
      preRequisite: "",
      type: "core",
    },
    {
      id: 12,
      code: "DCIT 309",
      title: "Embedded Systems and IoT",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
    {
      id: 12,
      code: "DCIT 311",
      title: "Machine Learning",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
  ],
};

export const YearFourSMFirstSem: programContent = {
  header: "Level 400 First Semester (Single Major)",
  description:
    "* Select 6-9 credits from the elective courses in addition to the core courses *",
  courses: [
    {
      id: 13,
      code: "DCIT 400",
      title: "Project",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 14,
      code: "DCIT 401",
      title: "Social, Legal, Ethical and Professional Issues",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 15,
      code: "DCIT 407",
      title: "Image Processing",
      credits: 3,
      preRequisite: "",
      type: "core",
    },
    {
      id: 16,
      code: "DCIT 403",
      title: "Designing Intelligent Agents",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
    {
      id: 17,
      code: "DCIT 405",
      title: "Statistical Models and Methods for Data Science",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
    {
      id: 18,
      code: "DCIT 411",
      title: "Bioinformatics",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
    {
      id: 19,
      code: "DCIT 417",
      title: "Network Performance Analysis and Modeling",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
    {
      id: 20,
      code: "DCIT 423",
      title: "Network Servers and Infrastructure",
      credits: 3,
      preRequisite: "",
      type: "elective",
    },
  ],
};
